/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -warn-error +9 -drop WasmSupport -tmpdir ./out -fsopt --cache_dir -fsopt ./out -fsopt --cache_checked_modules -skip-linking -skip-compilation -no-prefix HardCoding -no-prefix ParseDoor -no-prefix ParseIndicator -no-prefix ParseSpeed hardCoding.fst parseDoor.fst parseIndicator.fst parseSpeed.fst
  F* version: <unknown>
  KreMLin version: 8d03c65f
 */

#include "C.h"

bool uu___is_EXIT_SUCCESS(exit_code projectee)
{
  switch (projectee)
  {
    case EXIT_SUCCESS:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool uu___is_EXIT_FAILURE(exit_code projectee)
{
  switch (projectee)
  {
    case EXIT_FAILURE:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

