/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -warn-error +9 -drop WasmSupport -tmpdir ./out -fsopt --cache_dir -fsopt ./out -fsopt --cache_checked_modules -skip-linking -skip-compilation -no-prefix HardCoding -no-prefix ParseDoor -no-prefix ParseIndicator -no-prefix ParseSpeed hardCoding.fst parseDoor.fst parseIndicator.fst parseSpeed.fst
  F* version: <unknown>
  KreMLin version: 8d03c65f
 */

#ifndef __ParseDoor_H
#define __ParseDoor_H

#include "kremlib.h"


#include "HardCoding.h"

typedef struct fstar_uint8_s
{
  uint8_t value;
  struct_error error;
}
fstar_uint8;

fstar_uint8 parseDoor_body(uint32_t can_id, uint8_t can_dlc, uint8_t *data);

fstar_uint8 parseDoor(uint32_t can_id, uint8_t can_dlc, uint8_t *data);


#define __ParseDoor_H_DEFINED
#endif
