/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -warn-error +9 -drop WasmSupport -tmpdir ./out -fsopt --cache_dir -fsopt ./out -fsopt --cache_checked_modules -skip-linking -skip-compilation -no-prefix HardCoding -no-prefix ParseDoor -no-prefix ParseIndicator -no-prefix ParseSpeed hardCoding.fst parseDoor.fst parseIndicator.fst parseSpeed.fst
  F* version: <unknown>
  KreMLin version: 8d03c65f
 */

#ifndef __ParseSpeed_H
#define __ParseSpeed_H

#include "kremlib.h"


#include "HardCoding.h"

typedef struct fstar_uint16_s
{
  uint16_t value;
  struct_error error;
}
fstar_uint16;

fstar_uint16 parseSpeed_body(uint32_t can_id, uint8_t can_dlc, uint8_t *data);

fstar_uint16 parseSpeed(uint32_t can_id, uint8_t can_dlc, uint8_t *data);


#define __ParseSpeed_H_DEFINED
#endif
