/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verify -warn-error +9 -drop WasmSupport -tmpdir ./out -fsopt --cache_dir -fsopt ./out -fsopt --cache_checked_modules -skip-linking -skip-compilation -no-prefix HardCoding -no-prefix ParseDoor -no-prefix ParseIndicator -no-prefix ParseSpeed hardCoding.fst parseDoor.fst parseIndicator.fst parseSpeed.fst
  F* version: <unknown>
  KreMLin version: 8d03c65f
 */

#include "ParseSpeed.h"

fstar_uint16 parseSpeed_body(uint32_t can_id, uint8_t can_dlc, uint8_t *data)
{
  uint8_t first_speed_byte_u8 = data[0U];
  uint8_t second_speed_byte_u8 = data[1U];
  uint16_t first_speed_byte_u16 = (uint16_t)first_speed_byte_u8;
  uint16_t second_speed_byte_u16 = (uint16_t)second_speed_byte_u8;
  uint16_t
  ret = (second_speed_byte_u16 - (uint16_t)0xd0U) * (uint16_t)0xffU + first_speed_byte_u16;
  return ((fstar_uint16){ .value = ret, .error = { .code = (int32_t)0, .message = "" } });
}

fstar_uint16 parseSpeed(uint32_t can_id, uint8_t can_dlc, uint8_t *data)
{
  uint8_t v1 = data[1U];
  uint8_t v2 = data[2U];
  uint8_t v3 = data[3U];
  uint8_t v4 = data[4U];
  if
  (
    can_id
    == (uint32_t)0x1b4U
    && can_dlc == (uint8_t)5U
    && v1 >= (uint8_t)0xD0U
    && v2 == (uint8_t)0U
    && v3 == (uint8_t)0U
    && v4 == (uint8_t)0U
  )
    return parseSpeed_body(can_id, can_dlc, data);
  else
    return
      (
        (fstar_uint16){
          .value = (uint16_t)0U,
          .error = { .code = (int32_t)1, .message = "invalid arguments" }
        }
      );
}

